host: localhost
port: 7777
property: connectTimeout:5,compression:true
routes:
  - from: /his
    from_method: post
    to: localhost:8282/demo222
    to_method: post
    exchange_bean: com.oldtan.camel.processor.DefaultExchangeBean

  ## If you set to uri contain path variable，then set follow the below
  #  destination endpoint uri is:  http://localhost:8282/demo222/{id}
  - from: /demo222/{id}
    from_method: post
    to: localhost:8282
    to_method: post
    exchange_bean: com.oldtan.camel.processor.DefaultExchangeBean

  ## If destination endpoint is web SOAP service, then set to_method attributes value 'ws'
  - from: /tows
    from_method: post
    to: localhost:8080/ws
    to_method: ws
    exchange_bean: com.oldtan.camel.processor.DefaultWsExchangeBean
