host: localhost
port: 7777
property: connectTimeout:5
routes:
  - from: /his
    from_method: post
    to: localhost:8282/demo222
    to_method: post
    exchange_bean: com.oldtan.camel.processor.DefaultExchangeBean

  ## If you set to uri contain path variable，then you set follow the below
  #  actual to uri is:  http://localhost:8282/demo222/{id}
  - from: /demo222/{id}
    from_method: post
    to: localhost:8282
    to_method: post
    exchange_bean: com.oldtan.camel.processor.DefaultExchangeBean
